export const GET_DEMO_REQUEST = 'GET_DEMO_REQUEST';
export const GET_DEMO_SUCCESS = 'GET_DEMO_SUCCESS';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR';


export const GET_HERO_MARVEL_DATA_START = "GET_HERO_MARVEL_DATA_START";
export const GET_HERO_MARVEL_DATA_SUCCESS = "GET_HERO_MARVEL_DATA_SUCCESS";
export const GET_HERO_MARVEL_DATA_ERROR = "GET_HERO_MARVEL_DATA_ERROR";


